version: '3.8'

services:
  php:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: php /var/www/html/main.php start
    depends_on:
      - web
    networks:
      - app-network

  web:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network: